packages:
  - apps/demo
  - packages/expo-desktop
  - packages/expo-desktop/scripts
  - packages/expo-desktop-config-plugins
  - packages/expo-desktop-modules-core
  - packages/expo-desktop-prebuild-config
  - packages/expo-desktop-stubs
  - scripts

catalogs:
  base:
    "@tsconfig/node24": ^24.0.4
    "@types/node": ^24.12.2
    "@typescript/native-preview": ^7.0.0-dev.20260425.1
    typescript: ^5.9.3
    vitest: ^3.2.4
  react-native-81:
    "@expo/config": ^12.0.13
    "@expo/config-plugins": ^54.0.4
    "@expo/config-types": ^54.0.10
    "@expo/prebuild-config": ^54.0.8
    "@react-native/metro-config": ~0.81.0
    "@types/react": ~19.1.0
    expo: ^54.0.33
    react: 19.1.4
    react-native: 0.81.6
    react-native-macos: 0.81.7
    react-native-windows: 0.81.18
  react-native-82:
    "@expo/config": ^55.0.15
    "@expo/config-plugins": ^55.0.8
    "@expo/config-types": ^55.0.5
    "@expo/prebuild-config": ^55.0.16
    "@react-native/metro-config": ~0.82.0
    "@types/react": ~19.1.0
    expo: ^55.0.17
    react: 19.1.1
    react-native: 0.82.1
    react-native-windows: 0.82.5
  react-native-83:
    "@expo/config": ^55.0.15
    "@expo/config-plugins": ^55.0.8
    "@expo/config-types": ^55.0.5
    "@expo/prebuild-config": ^55.0.16
    "@react-native/metro-config": ~0.83.0
    "@types/react": ~19.2.0
    expo: ^55.0.17
    react: 19.2.0
    react-native: 0.83.6
  # Expo skipped from 0.83 (SDK 55) to 0.85 (SDK 56). The newer of the two may
  # be our least bad option for 0.84.
  # https://github.com/expo/expo/blob/sdk-56/templates/expo-template-bare-minimum/package.json
  react-native-84:
    "@expo/config": ~56.0.0-preview.12
    "@expo/config-plugins": ^56.0.5
    "@expo/config-types": ^56.0.4
    "@expo/prebuild-config": ^56.0.8
    "@react-native/metro-config": ~0.84.1
    "@types/react": ~19.2.0
    expo: ~56.0.0-preview.12
    react: 19.2.3
    react-native: 0.84.1
  react-native-85:
    "@expo/config": ~56.0.0-preview.12
    "@expo/config-plugins": ^56.0.5
    "@expo/config-types": ^56.0.4
    "@expo/prebuild-config": ^56.0.8
    "@react-native/metro-config": ~0.84.1
    "@types/react": ~19.2.0
    expo: ~56.0.0-preview.12
    react: 19.2.3
    react-native: 0.85.3

# Formerly onlyBuiltDependencies/neverBuiltDependencies/ignoredBuiltDependencies
allowBuilds:
  esbuild: false

nodeLinker: hoisted
