// AutolinkedNativeModules.g.cpp contents generated by "npx @react-native-community/cli autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from expo-desktop-modules-core
#include <winrt/ExpoModulesCore.h>

// Includes from expo-desktop-stubs
#include <winrt/ExpoDesktopStubs.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from expo-desktop-modules-core
    packageProviders.Append(winrt::ExpoModulesCore::ReactPackageProvider());
    // IReactPackageProviders from expo-desktop-stubs
    packageProviders.Append(winrt::ExpoDesktopStubs::ReactPackageProvider());
}

}
