name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"
      - "packages/expo-desktop/tsconfig.build.json"
      - "packages/expo-desktop/package.json"
      - "packages/expo-desktop/CHANGELOG.md"
      - "packages/expo-desktop-prebuild-config/package.json"
      - "packages/expo-desktop-prebuild-config/CHANGELOG.md"
      - "packages/expo-desktop-config-plugins/package.json"
      - "packages/expo-desktop-config-plugins/CHANGELOG.md"
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    # Matches the GitHub Environment name on each npm package’s "Trusted
    # publisher" config.
    environment: Stable Release
    permissions:
      # To push git tags
      contents: write
      # To publish to npm via OIDC
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest
          # cache: true

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
          # cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter expo-desktop --filter
          expo-desktop-config-plugins --filter expo-desktop-modules-core --filter expo-desktop-prebuild-config --filter expo-desktop-stubs

      # Build in order of dependency graph:
      # config-plugins → prebuild-config → expo-desktop.
      - name: Build expo-desktop-config-plugins
        working-directory: packages/expo-desktop-config-plugins
        run: node --run build

      - name: Build expo-desktop-prebuild-config
        working-directory: packages/expo-desktop-prebuild-config
        run: node --run build

      - name: Build expo-desktop
        working-directory: packages/expo-desktop
        run: node --run build

      - name: Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: node --run release:publish
